[project]
name = "bank-clients-ml"
version = "0.1.0"
description = "Machine learning project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fpdf2>=2.8.7",
    "ipython>=9.16.1",
    "lightgbm>=4.7.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.1",
    "pandas>=3.0.5",
    "pyarrow>=25.0.0",
    "scikit-learn>=1.9.0",
    "scipy>=1.18.0",
]

[project.scripts]
bank-clients-ml = "bank_clients_ml:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupytext>=1.19.5",
    "ruff>=0.16.1",
]

[tool.jupytext]
formats = "ipynb,md"
